- name: add NodeJS repository
  command: sh -c "curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -"

- name: make sure NodeJS server is installed
  yum: name=nodejs state=latest disable_gpg_check=yes

- name: clone Web App repository
  git: repo=https://github.com/ReCodEx/web-app.git dest={{ source_dir }}/webapp

- name: install dependencies
  command: npm install chdir={{ source_dir }}/webapp

- name: install pm2
  command: npm install -g pm2

- name: build the Web App
  command: npm run build chdir={{ source_dir }}/webapp

- name: run the application in NodeJS server
  command: pm2 start -f bin/server.js chdir={{ source_dir }}/webapp

- name: configure Apache proxy
  template: src="{{ role_path }}/templates/010-webapp.conf.j2" dest="/etc/httpd/conf.d/010-webapp.conf"
  notify:
      - restart apache

