- name: clone fileserver repository
  git: repo=https://github.com/ReCodEx/fileserver.git dest={{ source_dir }}/fileserver

- name: install python requirements
  pip: executable=/usr/bin/pip3 requirements={{ source_dir }}/fileserver/requirements.txt

- name: create fileserver working directory
  file: path=/var/recodex-fileserver state=directory mode=0777

- name: install python dependency for htpasswd module
  yum: name=python-passlib state=latest

- name: create htpasswd file with fileserver credentials
  htpasswd: path=/etc/httpd/recodex_htpasswd name="{{ fileserver_username }}" password="{{ fileserver_password }}" create=yes state=present

- name: setup fileserver inside Apache
  template: src="{{ role_path }}/templates/010-fileserver.conf.j2" dest=/etc/httpd/conf.d/010-fileserver.conf
  notify:
      - restart apache
