- name: install uwsgi dependencies
  yum: name=uwsgi,uwsgi-router-static,uwsgi-router-rewrite,uwsgi-plugin-python3 state=latest

- name: clone fileserver repository
  git: repo=https://github.com/ReCodEx/fileserver.git dest={{ source_dir }}/fileserver

- name: install python requirements
  pip: executable=/usr/bin/pip3 requirements={{ source_dir }}/fileserver/requirements.txt

- name: create fileserver working directory
  file: path=/var/recodex-fileserver state=directory mode=0777

- name: install python dependency for htpasswd module
  yum: name=python-passlib state=latest

- name: create htpasswd file with fileserver credentials
  htpasswd: path=/etc/httpd/recodex_htpasswd name="{{ fileserver_username }}" password="{{ fileserver_password }}" create=yes state=present

- name: setup fileserver as uwsgi service
  template: src="fileserver.ini.j2" dest=/etc/uwsgi.d/fileserver.ini owner=recodex group=recodex

- name: run uwsgi service
  service: name=uwsgi state=started enabled=yes

- name: setup fileserver proxy inside Apache
  template: src="010-fileserver.conf.j2" dest=/etc/httpd/conf.d/010-fileserver.conf
  notify:
      - restart apache

- name: enable port in firewall
  firewalld: port={{ fileserver_port }}/tcp state=enabled permanent=yes immediate=yes
  when: fileserver_firewall == 'yes'
