- name: clone fileserver repository
  git: repo=https://github.com/ReCodEx/fileserver.git dest={{ source_dir }}/fileserver

- name: install python requirements
  pip: executable=/usr/bin/pip3 requirements={{ source_dir }}/fileserver/requirements.txt

- name: create fileserver working directory
  file: path=/var/recodex-fileserver state=directory mode=0777

- name: setup fileserver inside Apache
  copy: src="{{ role_path }}/templates/010-fileserver.conf.j2" dest=/etc/httpd/conf.d/010-fileserver.conf
  notify:
      - restart apache
