- name: clone monitor repository
  git: repo=https://github.com/ReCodEx/monitor.git dest={{ source_dir }}/monitor

- name: install python requirements
  pip: executable=/usr/bin/pip3 requirements={{ source_dir }}/monitor/requirements.txt

- name: build RPM package
  command: python3 setup.py bdist_rpm --post-install ./monitor/install/postinst chdir={{ source_dir }}/monitor

- name: install monitor binary
  yum: name={{ source_dir }}/monitor/dist/recodex-monitor-0.2.0-1.noarch.rpm state=present

- name: configure monitor
  template: src="{{ role_path }}/templates/config.yml.j2" dest="/etc/recodex/monitor/config.yml" owner=recodex

- name: make sure monitor is running and enabled
  service: name=recodex-monitor state=started enabled=yes

