- name: make sure libarchive is installed
  yum: name=libarchive,libarchive-devel state=latest

- name: clone worker repository
  git: repo=https://github.com/ReCodEx/worker.git recursive=yes dest={{ source_dir }}/worker

- name: create build directory
  file: path={{ source_dir }}/worker/build state=directory mode=0755

- name: run cmake to generate the Makefile
  command: /usr/bin/cmake3 .. chdir={{ source_dir }}/worker/build/

- name: build RPM package
  make: chdir={{ source_dir }}/worker/build/ target=package params=NUM_THREADS=4

- name: install worker package
  yum: name={{ source_dir }}/worker/build/recodex-worker-0.1.2-1-x86_64.rpm state=present

- name: configure worker instance
  template: src="config.yml.j2" dest="/etc/recodex/worker/config-1.yml" owner=recodex

- name: make sure worker is running and enabled
  service: name=recodex-worker@1 state=started enabled=yes
