- name: make sure ZeroMQ is installed
  yum: name=zeromq,zeromq-devel state=latest

- name: install Remi repository for new PHP version
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present disable_gpg_check=yes

- name: enable the repository
  command: yum-config-manager --enable remi-php70

- name: make sure PHP and composer are installed
  yum: name=php,php-mysqlnd,php-pecl-zmq,composer state=latest disable_gpg_check=yes

- name: clone api repository
  git: repo=https://github.com/ReCodEx/api.git dest={{ source_dir }}/webapi

- name: install dependencies via composer
  command: composer install chdir={{ source_dir }}/webapi

- name: make sure cache is flushed
  file: path="{{ source_dir }}/webapi/temp/cache" state=absent

- name: create configuration file with database credentials
  template: src="config.local.neon.j2" dest="{{ source_dir }}/webapi/app/config/config.local.neon"

- name: install the Python MySQL module
  yum: name=MySQL-python state=latest

- name: create database 'recodex-api'
  mysql_db: name=recodex-api state=present

- name: create database user for api
  mysql_user: name={{ mysql_recodex_username }} password={{ mysql_recodex_password }} priv="recodex-api.*:ALL" state=present

- name: update database schema
  command: php www/index.php orm:schema-tool:update --force chdir="{{ source_dir }}/webapi"

- name: flush cache
  file: path="{{ source_dir }}/webapi/temp/cache" state=absent

- name: fill database with initial data
  command: php www/index.php db:fill chdir="{{ source_dir }}/webapi"

- name: flush cache
  file: path="{{ source_dir }}/webapi/temp/cache" state=absent

- name: give Apache privileges to source code tree
  file: path="{{ source_dir }}/webapi" owner=apache recurse=yes

- name: configure Apache
  template: src="010-webapi.conf.j2" dest=/etc/httpd/conf.d/010-webapi.conf
  notify:
      - restart apache

- name: enable port in firewall
  firewalld: port={{ webapi_public_port }}/tcp state=enabled permanent=yes immediate=yes
  when: webapi_firewall == 'yes'
