- name: clone broker repository
  git: repo=https://github.com/ReCodEx/broker.git recursive=yes dest={{ source_dir }}/broker

- name: create build directory
  file: path={{ source_dir }}/broker/build state=directory mode=0755

- name: run cmake to generate the Makefile
  command: /usr/bin/cmake3 .. chdir={{ source_dir }}/broker/build/

- name: build RPM package
  make: chdir={{ source_dir }}/broker/build/ target=package params=NUM_THREADS=4

- name: install broker package
  yum: name={{ source_dir }}/broker/build/recodex-broker-0.1.2-1-x86_64.rpm state=present

- name: configure broker instance
  template: src="config.yml.j2" dest="/etc/recodex/broker/config.yml" owner=recodex

- name: make sure broker is running and enabled
  service: name=recodex-broker state=started enabled=yes

